export const pagesRoutes = [
  ["v-18cc131e","/CHANGELOG.html",{"title":"2.0.0-alpha.26 (2022-08-19)"},[":md"]],
  ["v-73005554","/CONTRIBUTING.html",{"title":"Contribution Guides"},[":md"]],
  ["v-8daa1a0e","/",{"title":"Gungnir V2"},["/README.md"]],
  ["v-85e9b55e","/docs/links/",{"title":"Links"},["/docs/links/README.md"]],
  ["v-75639148","/docs/posts/2021-12-24-hello-word.html",{"title":"Hello Word 1"},[":md"]],
  ["v-56face48","/docs/posts/2021-12-25-hello-word-with-header-image.html",{"title":"Hello Word 2"},[":md"]],
  ["v-3295b4bc","/docs/posts/2022-05-23-hello-word-with-header-image-with-long-title.html",{"title":"Hello Word with a long title, it should require two lines to display"},[":md"]],
  ["v-32a21e1c","/docs/posts/2022-05-24-hello-word-4.html",{"title":"Hello World 4"},[":md"]],
  ["v-42bf7372","/docs/docs/advanced/analytics.html",{"title":"Analytics"},[":md"]],
  ["v-6ffd900e","/docs/docs/advanced/comment.html",{"title":"Comment"},[":md"]],
  ["v-521d91ea","/docs/docs/advanced/hitokoto.html",{"title":"Hitokoto"},[":md"]],
  ["v-6c8ee533","/docs/docs/advanced/icons.html",{"title":"Icons"},[":md"]],
  ["v-4481be77","/docs/docs/advanced/reading-time.html",{"title":"Reading Time"},[":md"]],
  ["v-385f7dfb","/docs/docs/advanced/rss.html",{"title":"RSS"},[":md"]],
  ["v-37afb146","/docs/docs/basic/config.html",{"title":"Configuration"},[":md"]],
  ["v-039e503a","/docs/docs/basic/content.html",{"title":"Content"},[":md"]],
  ["v-60036ae5","/docs/docs/basic/installation.html",{"title":"Installation"},[":md"]],
  ["v-686924a7","/docs/docs/basic/intro.html",{"title":"Introduction"},[":md"]],
  ["v-7a0e5692","/docs/docs/basic/search.html",{"title":"Search"},[":md"]],
  ["v-53a3d719","/docs/docs/md-enhance/chart.html",{"title":"Chart.js"},[":md"]],
  ["v-f7ab709a","/docs/docs/md-enhance/math.html",{"title":"Math Rendering"},[":md"]],
  ["v-4c8093ce","/docs/docs/md-enhance/mermaid.html",{"title":"Mermaid"},[":md"]],
  ["v-5f2bbbb8","/docs/docs/md-enhance/others.html",{"title":"Others"},[":md"]],
  ["v-237daf8c","/docs/docs/plugins/baidu-tongji.html",{"title":"plugin-baidu-tongji"},[":md"]],
  ["v-4b684183","/docs/docs/plugins/chart.html",{"title":"plugin-chart"},[":md"]],
  ["v-67884941","/docs/docs/plugins/giscus.html",{"title":"plugin-giscus"},[":md"]],
  ["v-2be99bb5","/docs/docs/plugins/intro.html",{"title":"Plugins"},[":md"]],
  ["v-26a513a0","/docs/docs/plugins/katex.html",{"title":"plugin-katex"},[":md"]],
  ["v-7ffce2de","/docs/docs/plugins/md-plus.html",{"title":"plugin-md-plus"},[":md"]],
  ["v-64d40bb8","/docs/docs/plugins/mermaid.html",{"title":"plugin-mermaid"},[":md"]],
  ["v-022e6963","/docs/docs/plugins/reading-time.html",{"title":"plugin-reading-time"},[":md"]],
  ["v-6412cce2","/docs/docs/plugins/rss.html",{"title":"plugin-rss"},[":md"]],
  ["v-3755e892","/packages/plugins/baidu-tongji/",{"title":"@renovamen/vuepress-plugin-baidu-tongji@next"},["/packages/plugins/baidu-tongji/README.md"]],
  ["v-6a94d8ae","/packages/plugins/chart/",{"title":"vuepress-plugin-chart@next"},["/packages/plugins/chart/README.md"]],
  ["v-624188c7","/packages/plugins/giscus/",{"title":"vuepress-plugin-giscus@next"},["/packages/plugins/giscus/README.md"]],
  ["v-4ffbb254","/packages/plugins/katex/",{"title":"@renovamen/vuepress-plugin-katex@next"},["/packages/plugins/katex/README.md"]],
  ["v-54113892","/packages/plugins/md-plus/",{"title":"@renovamen/vuepress-plugin-md-plus@next"},["/packages/plugins/md-plus/README.md"]],
  ["v-ff26e744","/packages/plugins/mermaid/",{"title":"@renovamen/vuepress-plugin-mermaid@next"},["/packages/plugins/mermaid/README.md"]],
  ["v-37b9b42e","/packages/plugins/reading-time/",{"title":"@renovamen/vuepress-plugin-reading-time@next"},["/packages/plugins/reading-time/README.md"]],
  ["v-5f9b05b5","/packages/plugins/rss/",{"title":"@renovamen/vuepress-plugin-reading-time@next"},["/packages/plugins/rss/README.md"]],
  ["v-557c5a22","/packages/plugins/search/",{"title":"@renovamen/vuepress-plugin-search"},["/packages/plugins/search/README.md"]],
  ["v-509e8cb2","/docs/zh/docs/advanced/analytics.html",{"title":"站点统计"},[":md"]],
  ["v-1f207539","/docs/zh/docs/advanced/comment.html",{"title":"评论"},[":md"]],
  ["v-f1515bc2","/docs/zh/docs/advanced/hitokoto.html",{"title":"一言"},[":md"]],
  ["v-32ef191e","/docs/zh/docs/advanced/icons.html",{"title":"图标支持"},[":md"]],
  ["v-6c7347a8","/docs/zh/docs/advanced/reading-time.html",{"title":"阅读时长"},[":md"]],
  ["v-02fc9eb4","/docs/zh/docs/advanced/rss.html",{"title":"RSS"},[":md"]],
  ["v-ab6b4bf0","/docs/zh/docs/basic/config.html",{"title":"基本配置"},[":md"]],
  ["v-01c272ef","/docs/zh/docs/basic/content.html",{"title":"内容"},[":md"]],
  ["v-5bfc9d60","/docs/zh/docs/basic/installation.html",{"title":"安装"},[":md"]],
  ["v-099f1ec8","/docs/zh/docs/basic/intro.html",{"title":"介绍"},[":md"]],
  ["v-edc9f13c","/docs/zh/docs/basic/search.html",{"title":"搜索"},[":md"]],
  ["v-019cc914","/docs/zh/docs/extension/deploy.html",{"title":"部署"},[":md"]],
  ["v-41652dcd","/docs/zh/docs/extension/resource.html",{"title":"资源"},[":md"]],
  ["v-02c6bc44","/docs/zh/docs/md-enhance/chart.html",{"title":"Chart.js"},[":md"]],
  ["v-ec5eddb0","/docs/zh/docs/md-enhance/math.html",{"title":"数学公式渲染"},[":md"]],
  ["v-83024b8e","/docs/zh/docs/md-enhance/mermaid.html",{"title":"Mermaid"},[":md"]],
  ["v-d7350826","/docs/zh/docs/md-enhance/others.html",{"title":"其他"},[":md"]],
  ["v-0f040737","/docs/zh/docs/plugins/baidu-tongji.html",{"title":"plugin-baidu-tongji"},[":md"]],
  ["v-498c6438","/docs/zh/docs/plugins/chart.html",{"title":"plugin-chart"},[":md"]],
  ["v-2de87d2c","/docs/zh/docs/plugins/giscus.html",{"title":"plugin-giscus"},[":md"]],
  ["v-2a0dbe6a","/docs/zh/docs/plugins/intro.html",{"title":"插件"},[":md"]],
  ["v-2a5cce36","/docs/zh/docs/plugins/katex.html",{"title":"plugin-katex"},[":md"]],
  ["v-74b04ff4","/docs/zh/docs/plugins/md-plus.html",{"title":"plugin-md-plus"},[":md"]],
  ["v-6a7a552d","/docs/zh/docs/plugins/mermaid.html",{"title":"plugin-mermaid"},[":md"]],
  ["v-24967de4","/docs/zh/docs/plugins/reading-time.html",{"title":"plugin-reading-time"},[":md"]],
  ["v-60bde584","/docs/zh/docs/plugins/rss.html",{"title":"plugin-rss"},[":md"]],
  ["v-debb1262","/packages/theme/",{"title":"Gungnir V2"},["/packages/theme/README.md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
